sudo: required
dist: trusty
language: perl

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libdb-dev libxml2-dev libxslt1-dev texlive texlive-fonts-extra texlive-latex-extra texlive-lang-cyrillic biber trang

install:
 - git clone https://github.com/KWARC/LaTeXML
 - cd LaTeXML
 - cpanm --installdeps .
 - cpanm -v .
 - cd ..
 - cp LaTeXML/lib/LaTeXML/texmf/latexml.sty sty

script:
 - export BIBINPUTS=`pwd`/lib/bib
 - export PATH=$PATH:`pwd`/LaTeXML/bin
 - export STEXDIR=`pwd`
 - export TEXINPUTS=`pwd`/sty
 - find . -name \*.tex | xargs touch
 - find . -name \*.dtx | xargs touch
 - find . -name \*.ins | xargs touch
 - make
