sudo: required
dist: trusty
language: perl

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libdb-dev libxml2-dev libxslt1-dev texlive texlive-fonts-extra texlive-latex-extra texlive-lang-cyrillic biber trang

script:
 - export BIBINPUTS=`pwd`/lib/bib
 - export STEXDIR=`pwd`
 - export TEXINPUTS=`pwd`/sty
 - find . -name \*.tex | xargs touch
 - find . -name \*.dtx | xargs touch
 - find . -name \*.ins | xargs touch
 - make
