name: CI

on: [push]

jobs:
    tests:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - name: Setup TexLive and Friends
              run: |
                sudo apt-get update
                sudo apt-get install -y texlive texlive-fonts-extra texlive-latex-extra texlive-lang-cyrillic biber
            - name: Show TexLive Version
              run: tex --version
            - name: Run Tests
              shell: bash
              run: |
                export BIBINPUTS=`pwd`/lib/bib
                export STEXDIR=`pwd`
                export TEXINPUTS=.//:`pwd`/sty//:$TEXINPUTS
                make test -B
